services:
  # 1. Die Flask Web-App
  web-app:
    image: ghcr.io/louner420/ki_trend_analyse:latest
    container_name: flask_web
    ports:
      - "8080:5002"
    volumes:
      - sqlite_data:/app/database
    environment:
      - DATA_PATH=/app/database
      - FLASK_DEBUG=0
      - PYTHONUNBUFFERED=1
    restart: always

  # 2. Der Scraper
  scraper:
    image: ghcr.io/louner420/ki_trend_analyse:latest
    container_name: ki_scraper
    # Startet den Scraper direkt aus dem Image
    command: python -u ai/daemon_scraper.py
    volumes:
      - sqlite_data:/app/database
    environment:
      - DATA_PATH=/app/database
      - PYTHONUNBUFFERED=1
    restart: on-failure

  # 3. Der KI-Processor
  ki-processor:
    image: ghcr.io/louner420/ki_trend_analyse:latest
    container_name: ki_logic
    command: python -u ai/main.py
    volumes:
      - sqlite_data:/app/database
    environment:
      - DATA_PATH=/app/database
      - PYTHONUNBUFFERED=1
    restart: always

volumes:
  sqlite_data: